name: Create release
on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
permissions:
  contents: write
  actions: write
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: 'actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0' # v7
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: install autotag binary
        run: |
          gh release download "$TAG" --repo "$REPO" --pattern "$BINARY"
          echo "$SHA256  $BINARY" | shasum -a 256 -c

          chmod +x "$BINARY"
          sudo mv "$BINARY" /usr/bin/autotag
        env:
          REPO: autotag-dev/autotag
          BINARY: autotag_linux_amd64
          TAG: v1.4.1
          SHA256: 7b34c34316b8dd57b43ca0b08454ba57baf6472bef4e5ea46215b6ef5cd96146
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit build, bump git tag, and create GitHub Release
        run: |-
          git config --global user.name 'islandora-community'
          git config --global user.email 'islandora-community@users.noreply.github.com'
          cp ./dist/main.js ./main.js
          git add main.js
          git commit -m "Adding main.js"
          git push origin main
          TAG=$(autotag)
          npm version "$TAG" --no-git-tag-version
          git tag "$TAG" || echo continue
          git push origin "$TAG"
          gh release create "$TAG" --title "$TAG" --generate-notes './main.js#main.js'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
